'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const root = path.resolve(__dirname, '..', '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
test('Vite package and Docker build contract are present', () => { const pkg = JSON.parse(read('package.json')); assert.equal(pkg.scripts.build, 'tsc --noEmit && vite build'); assert.ok(fs.existsSync(path.join(root, 'package-lock.json'))); const dockerfile = read('Dockerfile'); assert.match(dockerfile, /FROM node:20-slim AS frontend-build/); assert.match(dockerfile, /npm ci/); assert.match(dockerfile, /COPY --from=frontend-build \/frontend\/dist \.\/dist/); });
test('seven physical pages and shared components are independently defined', () => { for (const page of ['HomePage', 'WatchlistPage', 'AnalysisPage', 'PortfolioPage', 'ToolsPage', 'AlertsPage', 'AccountPage']) assert.ok(fs.existsSync(path.join(root, 'src', 'pages', `${page}.tsx`)), page); for (const component of ['HeroBalanceCard', 'CircleActionButton', 'BottomNav', 'Sidebar', 'AssetRow', 'NumericKeypad', 'States']) assert.ok(fs.existsSync(path.join(root, 'src', 'components', `${component}.tsx`)), component); const app = read('src/App.tsx'); for (const route of ['/watchlist', '/analysis', '/portfolio', '/tools', '/alerts', '/account']) assert.match(app, new RegExp(`path=\\"${route}\\"`)); });
test('design tokens are centralized and the old page shell is gone', () => { const tokens = read('src/styles/tokens.css'); for (const value of ['#080C18', '#1F212E', '#C1FF16', '#C7F091', '#DEF6A8']) assert.match(tokens, new RegExp(value)); const html = read('index.html'); assert.match(html, /id="root"/); assert.match(html, /src="\/src\/main\.tsx"/); assert.ok(html.length < 600); });
