import { FormEvent, useEffect, useState } from 'react';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { PageScaffold } from './PageScaffold'; import { api, cloudFeatureMessage } from '../lib/api';
import { useLiveQuote } from '../lib/useLiveQuote';
type List = { id:number; name:string; items?:{id?:number;ticker:string}[] };
function QuoteRow({ticker,onRemove}:{ticker:string;onRemove:()=>void}){const {quote,state}=useLiveQuote(ticker);return <div className="row"><strong>{ticker}</strong><span className={`connection ${state}`}>{state==='live'?'Live':state==='stale'?'Stale':state==='disconnected'?'Disconnected':'Reconnecting…'}</span><span>{quote?.price?.toFixed(2)||'—'}</span><button className="text-button danger" onClick={onRemove}>Remove</button></div>}
export default function WatchlistPage(){ const [lists,setLists]=useState<List[]>(); const [error,setError]=useState(''); const [status,setStatus]=useState(''); const [selected,setSelected]=useState<number>();
 const load=async()=>{try{const x=await api<{items:List[]}>('/api/watchlists');setLists(x.items);setSelected(s=>s||x.items[0]?.id)}catch(x){setError(cloudFeatureMessage(x))}}; useEffect(()=>{void load()},[]);
 const act=async(path:string,method:string,body?:object)=>{try{setError('');setStatus('Working…');await api(path,{method,body:body&&JSON.stringify(body)});setStatus('Saved.');await load()}catch(x){setStatus('');setError(cloudFeatureMessage(x))}};
 if(!lists&&!error)return <PageScaffold title="Watchlist" description="Named lists and live monitoring."><LoadingState/></PageScaffold>; if(!lists)return <PageScaffold title="Watchlist" description="Named lists and live monitoring."><ErrorState detail={error}/></PageScaffold>; const active=lists.find(x=>x.id===(selected||lists[0]?.id));
 return <PageScaffold title="Watchlist" description="Create lists and add/remove real tickers.">{error&&<ErrorState detail={error}/>}<p className="success">{status}</p><section className="card"><form className="inline-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/watchlists','POST',{name:f.get('name')});e.currentTarget.reset()}}><input name="name" required placeholder="New list name"/><button className="action-link">Create list</button></form><div className="tabs">{lists.map(x=><button key={x.id} className={active?.id===x.id?'selected':''} onClick={()=>setSelected(x.id)}>{x.name}</button>)}</div></section>{active&&<section className="card"><h2>{active.name}</h2><button className="text-button danger" onClick={()=>confirm('Delete this list?')&&act(`/api/watchlists/${active.id}`,'DELETE')}>Delete list</button><form className="inline-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(`/api/watchlists/${active.id}/items`,'POST',{ticker:String(f.get('ticker')).toUpperCase()});e.currentTarget.reset()}}><input name="ticker" required placeholder="Ticker"/><button className="action-link">Add ticker</button></form>{active.items?.map(i=><QuoteRow key={i.id||i.ticker} ticker={i.ticker} onRemove={()=>confirm(`Remove ${i.ticker}?`)&&act(`/api/watchlists/${active.id}/items?ticker=${i.ticker}`,'DELETE')}/>)}{!active.items?.length&&<EmptyState title="This list is empty" detail="Add an instrument above."/>}</section>}</PageScaffold>;
}
